"""
🟢 Node.js/Express Generator
"""
from typing import Dict, List
import json


class NodeGenerator:
    """Generate Node.js/Express backend applications."""

    @staticmethod
    def generate_project(name: str, config: Dict = None) -> Dict:
        """Generate a complete Node.js project."""
        config = config or {}

        files = {
            "package.json": json.dumps({
                "name": name,
                "version": "1.0.0",
                "description": "Generated by Yasmin AI",
                "main": "src/index.js",
                "scripts": {
                    "start": "node src/index.js",
                    "dev": "nodemon src/index.js",
                    "test": "jest",
                    "lint": "eslint src/"
                },
                "dependencies": {
                    "express": "^4.19.0",
                    "cors": "^2.8.5",
                    "helmet": "^7.1.0",
                    "morgan": "^1.10.0",
                    "dotenv": "^16.4.0",
                    "mongoose": "^8.4.0",
                    "jsonwebtoken": "^9.0.0",
                    "bcryptjs": "^2.4.3",
                    "express-rate-limit": "^7.3.0",
                    "compression": "^1.7.4"
                },
                "devDependencies": {
                    "nodemon": "^3.1.0",
                    "jest": "^29.7.0",
                    "eslint": "^8.57.0",
                    "supertest": "^7.0.0"
                }
            }, indent=2),

            "src/index.js": """const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const compression = require('compression');
const rateLimit = require('express-rate-limit');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3000;

// Security middleware
app.use(helmet());
app.use(cors());
app.use(compression());
app.use(morgan('combined'));

// Rate limiting
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 100
});
app.use(limiter);

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Routes
app.use('/api/health', require('./routes/health'));
app.use('/api/users', require('./routes/users'));
app.use('/api/projects', require('./routes/projects'));

// Error handling
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).json({ error: 'Something went wrong!' });
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
""",

            "src/routes/health.js": """const express = require('express');
const router = express.Router();

router.get('/', (req, res) => {
  res.json({ status: 'healthy', timestamp: new Date().toISOString() });
});

module.exports = router;
""",

            "src/routes/users.js": """const express = require('express');
const router = express.Router();

router.get('/', (req, res) => {
  res.json({ users: [] });
});

router.post('/', (req, res) => {
  res.status(201).json({ id: 'user_123', ...req.body });
});

module.exports = router;
""",

            "src/routes/projects.js": """const express = require('express');
const router = express.Router();

router.get('/', (req, res) => {
  res.json({ projects: [] });
});

router.post('/', (req, res) => {
  res.status(201).json({ id: 'proj_123', ...req.body });
});

module.exports = router;
""",

            ".env.example": """PORT=3000
MONGODB_URI=mongodb://localhost:27017/yasmin
JWT_SECRET=your-secret-key
NODE_ENV=development
""",

            ".eslintrc.json": json.dumps({
                "env": {"node": True, "es2021": True},
                "extends": "eslint:recommended",
                "parserOptions": {"ecmaVersion": "latest"},
                "rules": {}
            }, indent=2)
        }

        return {
            "framework": "node",
            "version": "20",
            "language": "javascript",
            "files": [{"path": k, "content": v} for k, v in files.items()],
            "total_files": len(files)
        }


generator = NodeGenerator()
