# ═══════════════════════════════════════════════════════════════════════════
# ║                    ياسمين دارك تكنولوجي - FastAPI                       ║
# ║         Backend مع 7 وكلاء ذكاء اصطناعي متوازيين + 500 مبرمج           ║
# ╚══════════════════════════════════════════════════════════════════════════╝

from fastapi import FastAPI, WebSocket, WebSocketDisconnect, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from contextlib import asynccontextmanager
import asyncio
import json
import uuid
from datetime import datetime, timedelta
from typing import List, Dict, Optional
import httpx

@asynccontextmanager
async def lifespan(app: FastAPI):
    print("🌸 ياسمين دارك تكنولوجي - بدء التشغيل")
    await init_agents()
    yield
    print("🌸 إيقاف التشغيل")

app = FastAPI(
    title="ياسمين دارك تكنولوجي",
    description="منصة بناء المشاريع البرمجية بالذكاء الاصطناعي - 500+ وكيل",
    version="3.0.0",
    lifespan=lifespan
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

security = HTTPBearer()

users_db: Dict[str, dict] = {}
projects_db: Dict[str, dict] = {}
agents_db: Dict[str, dict] = {}
websocket_connections: List[WebSocket] = []

from pydantic import BaseModel, EmailStr

class UserRegister(BaseModel):
    email: EmailStr
    password: str
    first_name: str
    last_name: str

class UserLogin(BaseModel):
    email: EmailStr
    password: str

class ProjectCreate(BaseModel):
    name: str
    description: str
    project_type: str
    requirements: Optional[str] = None

class AgentCommand(BaseModel):
    command: str
    project_id: Optional[str] = None

import jwt
from passlib.context import CryptContext

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
SECRET_KEY = "yasmin-dark-tech-secret-key-2024"
ALGORITHM = "HS256"

def create_token(data: dict):
    to_encode = data.copy()
    expire = datetime.utcnow() + timedelta(days=7)
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)

def verify_token(token: str):
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        return payload
    except:
        return None

async def get_current_user(credentials: HTTPAuthorizationCredentials = Depends(security)):
    token = credentials.credentials
    payload = verify_token(token)
    if not payload:
        raise HTTPException(status_code=401, detail="توكن غير صالح")
    user = users_db.get(payload.get("sub"))
    if not user:
        raise HTTPException(status_code=401, detail="المستخدم غير موجود")
    return user

class Agent:
    def __init__(self, name: str, role: str, icon: str, color: str):
        self.id = str(uuid.uuid4())
        self.name = name
        self.role = role
        self.icon = icon
        self.color = color
        self.status = "idle"
        self.current_task = None
        self.skills = []
        self.memory = []

    async def process(self, task: str, context: dict = None):
        self.status = "working"
        self.current_task = task
        await asyncio.sleep(1)
        result = await self.generate_code(task, context)
        self.status = "idle"
        self.current_task = None
        self.memory.append({"task": task, "result": result, "time": datetime.now().isoformat()})
        return result

    async def generate_code(self, task: str, context: dict = None):
        return {
            "agent": self.name,
            "code": f"# Generated by {self.name}\n# Task: {task}\n\nclass GeneratedProject:\n    pass",
            "files": [
                {"name": "main.py", "content": f"# {self.name} generated code"},
                {"name": "config.json", "content": "{\"version\": \"1.0.0\"}"}
            ],
            "suggestions": ["أضف اختبارات وحدة", "حسن الأداء", "أضف توثيق"]
        }

agents = {
    "ux_designer": Agent("مصمم UX", "تصميم الواجهات", "🎨", "#10B981"),
    "architect": Agent("المعماري", "تصميم المعمارية", "🏗️", "#3B82F6"),
    "developer": Agent("المطور", "كتابة الكود", "💻", "#8B5CF6"),
    "qa_engineer": Agent("مهندس الجودة", "اختبار الجودة", "🧪", "#F59E0B"),
    "devops": Agent("ديف أوبس", "النشر والتشغيل", "🚀", "#EF4444"),
    "security": Agent("خبير الأمان", "حماية النظام", "🔒", "#EC4899"),
    "game_dev": Agent("مطور الألعاب", "تطوير الألعاب", "🎮", "#06B6D4"),
}

programmers_pool = [
    {"id": f"prog_{i}", "name": f"مبرمج {i}", "specialty": ["Python", "JavaScript", "Rust", "Go", "C++"][i % 5], 
     "level": ["junior", "mid", "senior", "lead", "principal"][i % 5], "available": True}
    for i in range(500)
]

async def init_agents():
    print(f"✅ {len(agents)} وكلاء جاهزين")
    print(f"✅ {len(programmers_pool)} مبرمج في التيم")

class NeuralOrchestrator:
    def __init__(self):
        self.active_projects = {}
        self.task_queue = asyncio.Queue()

    async def create_project(self, project_data: ProjectCreate, user_id: str):
        project_id = str(uuid.uuid4())
        project = {
            "id": project_id,
            "name": project_data.name,
            "description": project_data.description,
            "type": project_data.project_type,
            "requirements": project_data.requirements,
            "user_id": user_id,
            "status": "planning",
            "agents": [],
            "code_files": [],
            "created_at": datetime.now().isoformat(),
            "progress": 0
        }
        await self.assign_agents(project)
        projects_db[project_id] = project
        self.active_projects[project_id] = project
        return project

    async def assign_agents(self, project: dict):
        agent_types = ["ux_designer", "architect", "developer", "qa_engineer", "devops"]
        if project["type"] == "game":
            agent_types.append("game_dev")
        if project["requirements"] and "security" in project["requirements"].lower():
            agent_types.append("security")

        for agent_type in agent_types:
            agent = agents[agent_type]
            project["agents"].append({
                "id": agent.id,
                "name": agent.name,
                "role": agent.role,
                "status": "assigned",
                "icon": agent.icon,
                "color": agent.color
            })
            asyncio.create_task(agent.process(
                f"بناء {project['type']}: {project['description']}",
                project
            ))
        project["status"] = "in_progress"

    async def get_progress(self, project_id: str):
        project = self.active_projects.get(project_id)
        if not project:
            return None
        total_agents = len(project["agents"])
        working = sum(1 for a in project["agents"] if a["status"] == "working")
        project["progress"] = min(100, int((working / total_agents) * 100))
        return project

orchestrator = NeuralOrchestrator()

@app.get("/api/health")
async def health_check():
    return {
        "status": "healthy",
        "version": "3.0.0",
        "agents": len(agents),
        "programmers": len(programmers_pool),
        "active_projects": len(orchestrator.active_projects),
        "timestamp": datetime.now().isoformat()
    }

@app.post("/api/auth/register")
async def register(user: UserRegister):
    if user.email in users_db:
        raise HTTPException(status_code=400, detail="البريد مستخدم بالفعل")
    user_id = str(uuid.uuid4())
    hashed_password = pwd_context.hash(user.password)
    users_db[user.email] = {
        "id": user_id,
        "email": user.email,
        "password": hashed_password,
        "first_name": user.first_name,
        "last_name": user.last_name,
        "created_at": datetime.now().isoformat()
    }
    token = create_token({"sub": user.email, "id": user_id})
    return {"token": token, "user": {"id": user_id, "email": user.email, "name": f"{user.first_name} {user.last_name}"}}

@app.post("/api/auth/login")
async def login(user: UserLogin):
    db_user = users_db.get(user.email)
    if not db_user or not pwd_context.verify(user.password, db_user["password"]):
        raise HTTPException(status_code=401, detail="بيانات الدخول غير صحيحة")
    token = create_token({"sub": user.email, "id": db_user["id"]})
    return {"token": token, "user": {"id": db_user["id"], "email": db_user["email"], "name": f"{db_user['first_name']} {db_user['last_name']}"}}

@app.get("/api/auth/me")
async def get_me(current_user: dict = Depends(get_current_user)):
    return {"user": {k: v for k, v in current_user.items() if k != "password"}}

@app.post("/api/projects")
async def create_project(project: ProjectCreate, current_user: dict = Depends(get_current_user)):
    result = await orchestrator.create_project(project, current_user["id"])
    return result

@app.get("/api/projects")
async def list_projects(current_user: dict = Depends(get_current_user)):
    user_projects = [p for p in projects_db.values() if p["user_id"] == current_user["id"]]
    return {"projects": user_projects}

@app.get("/api/projects/{project_id}")
async def get_project(project_id: str, current_user: dict = Depends(get_current_user)):
    project = projects_db.get(project_id)
    if not project or project["user_id"] != current_user["id"]:
        raise HTTPException(status_code=404, detail="المشروع غير موجود")
    return project

@app.get("/api/projects/{project_id}/progress")
async def get_project_progress(project_id: str):
    progress = await orchestrator.get_progress(project_id)
    if not progress:
        raise HTTPException(status_code=404, detail="المشروع غير موجود")
    return progress

@app.get("/api/agents")
async def list_agents():
    return {
        "agents": [
            {"id": a.id, "name": a.name, "role": a.role, "icon": a.icon, "color": a.color, "status": a.status}
            for a in agents.values()
        ],
        "programmers": {
            "total": len(programmers_pool),
            "available": sum(1 for p in programmers_pool if p["available"]),
            "senior": sum(1 for p in programmers_pool if p["level"] in ["senior", "lead", "principal"])
        }
    }

@app.post("/api/agents/command")
async def send_command(cmd: AgentCommand, current_user: dict = Depends(get_current_user)):
    results = []
    for agent in agents.values():
        result = await agent.process(cmd.command, {"project_id": cmd.project_id})
        results.append({"agent": agent.name, "result": result})
    return {"command": cmd.command, "results": results}

@app.get("/api/agents/{agent_id}/memory")
async def get_agent_memory(agent_id: str):
    for agent in agents.values():
        if agent.id == agent_id:
            return {"agent": agent.name, "memory": agent.memory}
    raise HTTPException(status_code=404, detail="الوكيل غير موجود")

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    websocket_connections.append(websocket)
    try:
        await websocket.send_json({
            "type": "welcome",
            "message": "🌸 مرحباً بك في ياسمين دارك تكنولوجي!",
            "agents": [a.name for a in agents.values()],
            "programmers": len(programmers_pool)
        })
        while True:
            data = await websocket.receive_json()
            if data.get("type") == "chat":
                user_msg = data.get("message", "")
                for agent in agents.values():
                    result = await agent.process(user_msg)
                    await websocket.send_json({
                        "type": "agent_response",
                        "agent": agent.name,
                        "icon": agent.icon,
                        "color": agent.color,
                        "message": result["code"][:200] + "...",
                        "timestamp": datetime.now().isoformat()
                    })
            elif data.get("type") == "create_project":
                project = await orchestrator.create_project(
                    ProjectCreate(**data.get("project", {})),
                    data.get("user_id", "anonymous")
                )
                await websocket.send_json({"type": "project_created", "project": project})
            elif data.get("type") == "ping":
                await websocket.send_json({"type": "pong", "time": datetime.now().isoformat()})
    except WebSocketDisconnect:
        websocket_connections.remove(websocket)
    except Exception:
        if websocket in websocket_connections:
            websocket_connections.remove(websocket)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
